spring.application.name=user-app
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/my-realm
spring.datasource.url=jdbc:postgresql://localhost:5432/practice
spring.datasource.username=postgres
spring.datasource.password=bitsflowtech

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# debug logs
logging.level.org.springframework.security=DEBUG